with open("Pass Holder" , "a") as f:
    a=input("Which app pass? ")
    u=input("Enter your username = ")
    p=input("Enter your passsword = ")
    f.write("\n")
    f.write(a)
    f.write("\n")
    f.write(u)
    f.write("\n")
    f.write(p)